### ISSUE TITLE
User can add an entry to the planner.

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/week-planner#1]
## 🖼 **Wireframes**
![Feature 1](https://user-images.githubusercontent.com/90408240/147511916-f1fcd01a-0540-4b62-ab47-fdf1a1afaba7.png)
 
## ✅ **Task List**

- [x] Create a styled page with an add entry button
- [x] Create a form to add an entry in html
- [x] Make all inputs of the add entry form `required`.
- [x] Listen for `submit` events  on the add entry form and: 
  - [x] Put the form values in a new object
  - [x] Reset the form inputs
- [x] Verify that new entries are saved to local storage along with the rest of the data model on page reload.
- [x] When the user clicks "Add Entry" button, Add Entry modal appears
- [x] After the entry is saved, the modal is hidden again
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
