### ISSUE TITLE
User can view the total number of entries per day.

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/week-planner#10]
## 🖼 Wireframes ##
![feature-5](https://user-images.githubusercontent.com/90408240/150655685-1e332ef2-b47d-4e10-b9f8-03ff453a0192.png)

## ✅  Task List ##
- [x] Style the numbers in span elements inside the week buttons in html
- [x] update the numbers dynamically in javascript: 
   - [x] create a function called showNumberOfEntries that queries for week buttons and the span elements, compare for data-view to make sure they match, find the number of entries based on the length of all trs (minus the blank ones) and update innerHTML on the span 
- [x]  Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x]  Test all functionality again in a private browsing session.
- [x] Fix all errors.
