### ISSUE TITLE
User can view entries by day.

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/week-planner#3]
## 🖼 **Wireframes**
![Feature 2](https://user-images.githubusercontent.com/90408240/147795087-62e06bb3-6a60-422f-b224-655dde387e41.png)

## ✅ **Task List**

- [x] Table Creation 
  - [x] Layout table in HTML
  - [x] Create the table skeleton using the DOM
- [x] Data Filtering 
  - [x] Filter the data for Monday
  - [x] Sort the times listed for Monday in order
  - [x] Ensure filtered data is funneled in in chart and defaulting to Monday table/data when user hits clicks 'submit' on the new entry form
  - [x] Ensure table is updated updated in real time after user clicks 'submit'
- [x] Data appearance on the page
  - [x] By default the entries for Monday are shown
  - [x] The 'Scheduled Events for Monday' element changes to 'Scheduled Events for Tuesday' when the Tuesday box was clicked (and shows Tuesday events)
  - [x] Ensure all the weekday buttons are functioning like the Monday & Tuesday buttons
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
