### ISSUE TITLE
User can update an entry.

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/week-planner#6]
## 🖼 **Wireframes**
![Feature-3](https://user-images.githubusercontent.com/90408240/149849892-e3b80d9d-3695-44d6-866d-ffe33e7a11e2.png)

## ✅ **Task List**
- [x] Create update button for each table row and style it 
- [x] Show the update buttons on each active table row 
- [x] Add a 'click' EventListenerto the update buttons:
   - [x] Set data.editing to value of the data.entry being edited
   - [x] Open the Modal 
   - [x] Ensure the Modal heading is updated to 'Update Entry'
   - [x] Pre-fill the modal with the data from the entry that is being updated 
   - [x] After the user clicks submit, ensure data from that row is updated to the new values and set data.editing back to null
   - [x] Ensure this works for all days of the weeks (and the user can change times, dates, and descriptions accordingly)
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
