### ISSUE TITLE
User can delete an entry.

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/week-planner#8]
## 🖼Wireframes ##
![feature-4](https://user-images.githubusercontent.com/90408240/149863562-3be1d759-43d7-4531-b500-6e0f3e8b5d82.png)

## ✅ Task List ##
- [x] Style delete button and add to each active table row
- [x] Create and style a modal with: 
   - [x] 'Delete Entry' heading
   - [x] 'Are you sure you want to delete this entry?' subheading 
   - [x] 'Yes' & 'No' buttons
- [x] addEventListener on the delete button to open the delete-specific modal
- [x] addEventListener on the delete-specific modal buttons:
   - [x] 'No' should take user back to view prior to modal opening with no changes
   - [x] 'Yes' should delete the selected entry
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
